node {

    checkout scm

    docker.withRegistry('https://tomjfrog.jfrog.io/artifactory/dockerociexamples-docker', 'jenkins-username-and-password') {

        def myImage = docker.build('tomjfrog.jfrog.io/dockerociexamples-dev/fat-manifest:latest')

        myImage.push()
    }

}